repos:
  - repo: local
    hooks:
      - id: commit-message
        name: "commit_message: Commit message check"
        entry: uv run commit-check --message --author-name --author-email --commit-signoff --config scripts/.commit-check.yaml
        language: system
        pass_filenames: false
        always_run: true

      - id: commit-message
        name: "commit_message: BUGFIX must include fixes=sha1|unknown"
        entry: uv run scripts/check_commit_message.py --bugfix_check
        language: system
        pass_filenames: false
        always_run: true

      - id: commit-message
        name: "commit_message: All commit message lines must be <= 72 chars"
        entry: uv run scripts/check_commit_message.py --length
        language: system
        pass_filenames: false
        always_run: true

      - id: scripts
        alias: scripts-lint
        name: "scripts: uv run ruff check"
        entry: uv run ruff check scripts
        language: system
        pass_filenames: false
        always_run: true

      - id: scripts
        alias: scripts-static-check
        name: "scripts: uv run ty check"
        entry: uv run ty check scripts
        language: system
        pass_filenames: false
        always_run: true

      - id: bot
        alias: lint
        name: "bot: npm run lint"
        entry: npm run lint
        language: system
        pass_filenames: false
        always_run: true

      - id: bot
        alias: build
        name: "bot: npm run build"
        entry: npm run build
        language: system
        always_run: true
        pass_filenames: false


      - id: bot
        alias: tests
        name: "bot: npm test"
        entry: npm test
        language: system
        pass_filenames: false
        always_run: true
