[project]
name = "whatsapp-bot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "commit-check>=0.10.1",
    "pre-commit>=4.2.0",
    "ruff>=0.12.3",
    "ty>=0.0.1a14",
]
