name: CD - Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_FULL_REPO: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO }}

jobs:
  wait:
    name: Wait for All CI workflows
    uses: ./.github/workflows/wait-for-workflows.yaml
    with:
      workflow_files: |
        ci-bot.yaml
        ci-docker.yaml
        ci-scripts.yaml
        ci-commit.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: wait
    if: needs.wait.outputs.all_passed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image with SHA tag
        run: |
          docker pull ${{ env.DOCKER_FULL_REPO }}:${{ github.sha }}

      - name: Tag image as latest
        run: |
          docker tag ${{ env.DOCKER_FULL_REPO }}:${{ github.sha }} ${{ env.DOCKER_FULL_REPO }}:latest

      - name: Push latest Docker tag
        run: |
          docker push ${{ env.DOCKER_FULL_REPO }}:latest
