name: CI - Bot

on:
  push:
    branches:
      - main
      - "test*"
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Build project
        run: npm run build:check

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: npm test
