name: CI - Commit Message

on:
  push:

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and uv Machine
        uses: ./.github/actions/setup-python-uv

      - name: Check Commit Message
        run: uv run pre-commit run commit-message
