name: CI - Docker

on:
  push:
    branches:
      - main
      - "test*"
  pull_request:
    branches:
      - main


env:
  DOCKER_FULL_REPO: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with tags
        run: >
          docker build
          -t ${{ env.DOCKER_FULL_REPO }}:latest
          -t ${{ env.DOCKER_FULL_REPO }}:${{ github.sha }}
          .

      - name: Push Docker image to remote registry with the sha1
        run: |
          docker push ${{ env.DOCKER_FULL_REPO }}:${{ github.sha }}
