name: CI/CD

on:
  push:
  pull_request:

env:
  DOCKER_USERNAME: theitamarshalev
  DOCKER_REPO: theitamarshalev/whatsapp_bot

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Build project
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: npm test

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with tags
        run: >
          docker build
          -t ${{ env.DOCKER_REPO }}:latest
          -t ${{ env.DOCKER_REPO }}:${{ github.sha }}
          .

      - name: Push Docker image to remote registry with the sha1
        run: |
          docker push ${{ env.DOCKER_REPO }}:${{ github.sha }}

  deploy-docker:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [build, lint, test, build-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image with SHA tag
        run: |
          docker pull ${{ env.DOCKER_REPO }}:${{ github.sha }}

      - name: Tag image as latest
        run: |
          docker tag ${{ env.DOCKER_REPO }}:${{ github.sha }} ${{ env.DOCKER_REPO }}:latest

      - name: Push latest Docker tag
        run: |
          docker push ${{ env.DOCKER_REPO }}:latest
